export const FASHION_KEYWORDS = [
  "Bollywood Glam",
  "K-Pop Streetwear",
  "Chikankari Fusion",
  "Saree Draping",
  "Indo-Western Fusion",
  "Cottagecore Saree",
  "Cottagecore Aesthetic",
  "Y2K Fashion",
  "Y2K Bollywood",
  "Downtown Girl",
  "Dark Academia",
  "Light Academia",
  "Dopamine Dressing",
  "Gen-Z Kurtis",
  "Khadi Streetwear",
  "Modern Handlooms",
  "Banarasi Corsets",
  "Bandhani Blazers",
  "Goth Lehenga",
  "Cyberpunk Sherwani",
  "Athleisure Kurta",
  "Ajrakh Co-ords",
  "Sustainable Silk",
  "Phulkari Jackets",
  "Minimalist Ethnic",
  "Indie Aesthetic",
  "Boho Chic Fusion",
  "Regencycore Anarkalis",
  "Oversized Kurtas",
  "Sneakers with Sarees",
  "Block Print Denim",
  "Zardozi Sneakers",
  "Tie-Dye Dupattas",
  "Neon Lehengas",
  "Patola Pantsuits",
  "Pastel Sherwanis",
  "Mirrorwork Corsets",
  "Eco-friendly Dyeing",
  "Denim Sarees",
  "Linen Dhotis",
  "Bandhgala Streetwear",
  "Heavy Metal Ethnic",
  "Goblincore Fusion",
  "Soft Girl Kurtis",
  "Royal Heritage Core",
  "Kanjeevaram Blazers",
  "Batik Shirtings",
  "Shibori Fusion",
  "Jute Accessories",
  "Tribal Print Capes",
  "Corset Cholis",
  "Trench Coat Sarees",
  "Hand-painted Organza",
  "Mirrorwork Jackets",
  "Kalamkari Overcoats",
  "Chanderi Bomber Jackets",
  "Kantha Stitch Denim",
  "Dabu Print Co-ords",
  "Kashmiri Kaftans",
  "Lakhnavi Fusion",
  "Ikats Blazers",
  "Pashmina Streetwear",
  "Vintage Bollywood",
  "Glow-in-the-dark Lehengas",
  "Brocade Jumpsuits",
  "Gingham Kurtis",
  "Old Money Aesthetic",
  "Grunge Aesthetic",
  "Balletcore",
  "Coquette Aesthetic"
];
